.PHONY: clean All

All:
	@echo "----------Building project:[ Lexer - Debug ]----------"
	@cd "Lexer" && "$(MAKE)" -f  "Lexer.mk"
clean:
	@echo "----------Cleaning project:[ Lexer - Debug ]----------"
	@cd "Lexer" && "$(MAKE)" -f  "Lexer.mk" clean
